apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-service
  template:
    metadata:
      labels:
        app: banking-service
    spec:
      containers:
        - name: banking-service
          image: banking-service:k8s-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # DATABASE
            - name: DB_URL
              value: "postgres:5432/banking-service"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: DB_PASSWORD

            # REDIS
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            # RABBITMQ
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"

            # JWT & MAIL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: JWT_SECRET
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: MAIL_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOKI_ENABLED
              value: "true"
            - name: LOGGING_LOKI_ENABLED
              value: "true"
            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: banking
spec:
  selector:
    app: banking-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort